services:
  - type: web
    name: tomobilti-platform
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: tomobilti-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://tomobilti-platform.onrender.com
    healthCheckPath: /api/cars

databases:
  - name: tomobilti-db
    plan: free
    databaseName: tomobilti
    user: tomobilti_user

