services:
  - type: web
    name: sharewheelz-platform
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sharewheelz-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://sharewheelz-platform.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
    healthCheckPath: /api/health

databases:
  - name: sharewheelz-db
    plan: free
    databaseName: sharewheelz
    user: sharewheelz_user

